version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - mvn clean
      - mvn install
      - docker ps
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

artifacts:
  files: '**/*'