version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo starting tests...
      - mvn install

  build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/a9c6e8c1
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 874965955493.dkr.ecr.us-east-1.amazonaws.com
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 874965955493.dkr.ecr.us-east-1.amazonaws.com/dev-ce2-blossom-ecr-ms-blossom-test:latest .
      - echo Tagging Docker Image ...
      - docker push 874965955493.dkr.ecr.us-east-1.amazonaws.com/dev-ce2-blossom-ecr-ms-blossom-test:latest
      - printf '[{"name":"dev-ce2-blossom-con-ms-blossom-test","imageUri":"874965955493.dkr.ecr.us-east-1.amazonaws.com/dev-ce2-blossom-ecr-ms-blossom-test:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml