
version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - mvn clean
      - mvn install
      - docker ps
      - aws ecr get-login --no-include-email

artifacts:
  files: '**/*'