version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:

    commands:
      - mvn clean
      - mvn install
      - docker ps
      - echo Logging in to Amazon ECR...
      - aws --version
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo $IMAGE_TAG

  build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 874965955493.dkr.ecr.us-east-1.amazonaws.com
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 874965955493.dkr.ecr.us-east-1.amazonaws.com/dev-ce2-blossom-ecr-ms-blossom-test:latest .
      - echo Tagging Docker Image ...
      - docker push 874965955493.dkr.ecr.us-east-1.amazonaws.com/dev-ce2-blossom-ecr-ms-blossom-test:latest
      - printf '[{"name":"dev-ce2-blossom-con-ms-blossom-test","imageUri":"874965955493.dkr.ecr.us-east-1.amazonaws.com/dev-ce2-blossom-ecr-ms-blossom-test:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml